CREATE DATABASE ksuhkcom_USER
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE ksuhkcom_USER.Users (
UserID INT unsigned NOT NULL AUTO_INCREMENT,
UserName CHAR(8) DEFAULT NULL,
UserUsername VARCHAR(32) DEFAULT NULL,
UserPassword CHAR(64) DEFAULT NULL,
UserSchool TINYINT unsigned DEFAULT NULL,
UserGrade TINYINT unsigned DEFAULT NULL,
UserMajor TINYINT unsigned DEFAULT NULL,
UserPhoneNo CHAR(9) DEFAULT NULL,
UserEmail VARCHAR(64) DEFAULT NULL,
UserBirth date DEFAULT NULL,
UserKakaoID VARCHAR(32) DEFAULT NULL,
UserRegister DATETIME DEFAULT NULL,
UserAcceptance TINYINT unsigned DEFAULT 1,
PRIMARY KEY (UserID)
) ENGINE = INNODB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

INSERT INTO ksuhkcom_USER.Users (UserName, UserUsername, UserPassword, UserSchool, UserAcceptance) VALUES ('관리자', 'ksuhkadmin', '998ed4d621742d0c2d85ed84173db569afa194d4597686cae947324aa58ab4bb', 0, 2);
/* default password = '1111' */



CREATE DATABASE ksuhkcom_STAFF
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE ksuhkcom_STAFF.Staffs (
StaffID INT unsigned NOT NULL AUTO_INCREMENT,
StaffName CHAR(8) DEFAULT NULL,
StaffEngName VARCHAR(32) DEFAULT NULL,
StaffPosition VARCHAR(32) DEFAULT NULL,
StaffSchool TINYINT unsigned DEFAULT NULL,
StaffPhoneNo CHAR(9) DEFAULT NULL,
StaffEmail VARCHAR(64) DEFAULT NULL,
StaffImage CHAR(64) DEFAULT NULL,
priority TINYINT unsigned DEFAULT NULL,
PRIMARY KEY (StaffID)
) ENGINE = INNODB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;



CREATE DATABASE ksuhkcom_NOTICE
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE ksuhkcom_NOTICE.Notice (
PostID INT unsigned NOT NULL AUTO_INCREMENT,
PostTitle VARCHAR(64) DEFAULT NULL,
PostPostdate DATETIME DEFAULT NULL,
PostUpdate DATETIME DEFAULT NULL,
PostCategory TINYINT unsigned DEFAULT NULL,
PostContent TEXT DEFAULT NULL,
PostImage CHAR(64) DEFAULT NULL,
PRIMARY KEY (PostID)
) ENGINE = INNODB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;



CREATE DATABASE ksuhkcom_EVENT
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE ksuhkcom_EVENT.Event (
EventID INT unsigned NOT NULL AUTO_INCREMENT,
EventTitle VARCHAR(64) DEFAULT NULL,
EventPostdate DATETIME DEFAULT NULL,
EventUpdate DATETIME DEFAULT NULL,
EventStart DATETIME DEFAULT NULL,
EventEnd DATETIME DEFAULT NULL,
EventAddress VARCHAR(255) DEFAULT NULL,
EventLatitude DECIMAL(10, 8) DEFAULT NULL,
EventLongitude DECIMAL(11, 8) DEFAULT NULL,
EventCurrency TINYINT unsigned DEFAULT 0,
EventCost INT unsigned DEFAULT NULL,
EventMaxInvite INT unsigned DEFAULT 0,
EventInviteEnable TINYINT unsigned DEFAULT 1,
EventContent TEXT DEFAULT NULL,
EventImage CHAR(64) DEFAULT NULL,
EventStatus TINYINT unsigned DEFAULT 1,
PRIMARY KEY (EventID)
) ENGINE = INNODB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;



CREATE DATABASE ksuhkcom_SPONSOR
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE ksuhkcom_SPONSOR.Sponsor (
SponsorID INT unsigned NOT NULL AUTO_INCREMENT,
SponsorTitle VARCHAR(64) DEFAULT NULL,
SponsorImage CHAR(64) DEFAULT NULL,
PRIMARY KEY (SponsorID)
) ENGINE = INNODB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;



CREATE DATABASE ksuhkcom_IMAGE
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE ksuhkcom_IMAGE.Image (
ImageID INT unsigned NOT NULL AUTO_INCREMENT,
ImageUploaddate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ImageHash char(64) DEFAULT NULL,
ImageType varchar(16) NOT NULL DEFAULT '',
ImageSize INT unsigned NOT NULL,
ImageData MEDIUMBLOB NOT NULL,
PRIMARY KEY (ImageID)
) ENGINE = INNODB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;



CREATE DATABASE ksuhkcom_FREE
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE ksuhkcom_FREE.Freeboard (
PostID INT unsigned NOT NULL AUTO_INCREMENT,
UserID INT unsigned NOT NULL,
PostTitle VARCHAR(64) DEFAULT NULL,
PostPostdate DATETIME DEFAULT NULL,
PostUpdate DATETIME DEFAULT NULL,
PostContent TEXT DEFAULT NULL,
PostImage CHAR(64) DEFAULT NULL,
PostStatus TINYINT unsigned DEFAULT 1,
PostReportUser INT unsigned NOT NULL,
PostReport TEXT DEFAULT NULL,
PRIMARY KEY (PostID)
) ENGINE = INNODB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE ksuhkcom_FREE.Image (
ImageID INT unsigned NOT NULL AUTO_INCREMENT,
ImageUploaddate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ImageHash char(64) DEFAULT NULL,
ImageType varchar(16) NOT NULL DEFAULT '',
ImageSize INT unsigned NOT NULL,
ImageData MEDIUMBLOB NOT NULL,
PRIMARY KEY (ImageID)
) ENGINE = INNODB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;



CREATE DATABASE ksuhkcom_BUYANDSELL
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE ksuhkcom_BUYANDSELL.BuyAndSell (
BASID INT unsigned NOT NULL AUTO_INCREMENT,
UserID INT unsigned NOT NULL,
BASTitle VARCHAR(64) DEFAULT NULL,
BASPostdate DATETIME DEFAULT NULL,
BASUpdate DATETIME DEFAULT NULL,
BASType TINYINT unsigned DEFAULT 1,
BASPrice INT unsigned DEFAULT NULL,
BASContent TEXT DEFAULT NULL,
BASStatus TINYINT unsigned DEFAULT 1,
BASImages TINYINT unsigned DEFAULT 0,
BASTopImage char(64) DEFAULT NULL,
BASReportStatus TINYINT unsigned DEFAULT 1,
BASReportUser INT unsigned NOT NULL,
BASReport TEXT DEFAULT NULL,
BASView INT unsigned DEFAULT 0,
PRIMARY KEY (BASID)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

CREATE TABLE ksuhkcom_BUYANDSELL.TempImage (
UserID INT unsigned NOT NULL,
ImageUploaddate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ImageHash char(64) DEFAULT NULL,
ImageType varchar(16) NOT NULL DEFAULT '',
ImageSize INT unsigned NOT NULL,
ImageData MEDIUMBLOB NOT NULL
) ENGINE = INNODB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;


